'use client'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'
import Navbar from './components/navbar/Navbar.jsx'
import Footer from './components/footer/Footer.jsx'
import AnimatedCursor from 'react-animated-cursor'


const NunitoSans = Nunito_Sans({ subsets: ['latin']})

export const metadata = {
  title: 'Van Leeuwen Media',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={NunitoSans.className}>
        
        <Navbar />
        {children}
        <Footer />
        <AnimatedCursor
          innerSize={20}
          outerSize={20}
          color='255, 133, 0'
          outerAlpha={0.2}
          innerScale={0.5}
          outerScale={5}
        />
        </body>
    </html>
  )
}
